# Generated by Django 5.1.1 on 2024-09-16 15:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarItems',
            fields=[
                ('name', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=2000)),
                ('model_number', models.IntegerField()),
                ('user_reviews', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='MoodEntry',
        ),
    ]
