# Generated by Django 5.1.1 on 2024-10-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_caritems_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caritems',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='caritems',
            name='user_reviews',
            field=models.TextField(max_length=500),
        ),
    ]
