# Generated by Django 5.1.1 on 2024-10-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_caritems_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caritems',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
