# Generated by Django 5.1.1 on 2024-10-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_caritems_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caritems',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='caritems',
            name='model_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='caritems',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='caritems',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
